In [57]:
import numpy as np

x = np.reshape(np.arange(0, 3*3*3, 1), (3,3,3))
b = np.array([3,8,7])
print(x)
y = x.reshape((-1,3))
print(y-b)
print(np.argmin((y-b), axis=1))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[-3 -7 -5]
 [ 0 -4 -2]
 [ 3 -1  1]
 [ 6  2  4]
 [ 9  5  7]
 [12  8 10]
 [15 11 13]
 [18 14 16]
 [21 17 19]]
[1 1 1 1 1 1 1 1 1]


In [130]:
print(y.shape)

(3,)


In [131]:
print(x[:,1].shape)

(3,)


In [132]:
print(x*2)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [133]:
print(x@y)

[ 8 26 44]


In [134]:
print(2*x@y)

[16 52 88]


In [135]:

a = np.reshape(np.arange(0, 12, 1), (4,3))
b = np.array([1,0,1])

print(a)
print(b * a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  0  2]
 [ 3  0  5]
 [ 6  0  8]
 [ 9  0 11]]
